package com.example.BlackboxBackend.DTO;

public enum RoleEnum {
    SUPER_ADMIN,
    ADMIN,
    WORKER
}

//SUPER ADMIN -> WILL DO ALL THE WORKS
//ADMIN -> CAN DO WITHIN THE DEPARTMENT
//WORKER -> CAN ONLY RESPOND TO THE ISSUES AND RESOLVE IT
