package com.example.BlackboxBackend.DTO;

public enum RoleEnum {
    SUPER_ADMIN,
    ADMIN,
    WORKER
}

//SUPER ADMIN -> CREATION OF DEPARTMENT | CREATION OF STAFF | RESOLVE ISSUES | DASHBOARD DEPARTMENT WISE | MAIN DASHBOARD
//ADMIN -> CAN ONLY CREATE STAFF WITHIN DEPARTMENT | RESOLVE ISSES | DASHBOARD
//WORKER -> CAN ONLY RESPOND TO THE ISSUES AND RESOLVE IT
